export const projects = [
  {
    title: 'E-Commerce',
    description: "E-commerce website using React, Redux, Hooks,Node.js, Express, paypal  and MongoDB",
      image: 'https://i.imgur.com/YzuvbGTl.jpg',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/sunnextt/proshopstore',
    visit: 'https://proshopshoppingapp.herokuapp.com/',
    id: 0,
  },
    {
    title: 'E-Commerce',
    description: "E-commerce website using React, Redux, Hooks, paystack and Firebase",
    image: 'https://i.imgur.com/1ljhAbal.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/sunnextt/React-ecommerce',
    visit: 'https://ecommerce-website-71213.web.app/',
    id: 1,
  },
  {
    title: 'Take-Note App',
    description:"TakeNote is a free, open-source notes app for the web. It is a demo project only. Your notes are saved in local storage and will not be permanently persisted, but are available for download.",
    image: 'https://i.imgur.com/WFEWn4rm.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/sunnextt/tn-taker.git',
    visit: 'https://tn-taker.vercel.app/',
    id: 2,
  },
  {
    title: 'charity web App',
    description: "",
      image: 'https://i.imgur.com/gQWR831l.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://github.com/sunnextt/charity-application',
    visit: 'https://sua-charity.netlify.app/',
    id: 3,
  },
  {
    title: 'redux gear cart',
    description: "A basic redux cart application",
    image: 'https://i.imgur.com/UwOTmcPl.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://redux-cart-app.netlify.app/',
    visit: 'https://redux-cart-app.netlify.app/',
    id: 4,
  },
  {
    title: 'Flight Status web app',
    description: "A web application for fetching flight time status",
    image: 'https://i.imgur.com/rNkyNwhm.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/sunnextt/flight-web-app',
    visit: 'https://aviationflightstatus.netlify.app/',
    id: 6,
  },
  {
    title: 'Joke App',
    description: "This is joke web application",
    image: 'https://i.imgur.com/7gnFdNql.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/sunnextt/joke_web_app',
    visit: 'https://jokeapplic.netlify.app/',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];