export const projects = [
  {
    title: 'E-Commerce',
    description: "",
      image: 'https://i.imgur.com/YzuvbGTl.jpg',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://proshopshoppingapp.herokuapp.com/',
    visit: 'https://proshopshoppingapp.herokuapp.com/',
    id: 0,
  },
    {
    title: 'E-Commerce',
    description: "",
    image: 'https://i.imgur.com/1ljhAbal.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://ecommerce-website-71213.web.app/',
    visit: 'https://ecommerce-website-71213.web.app/',
    id: 1,
  },
  {
    title: 'E-Commerce',
    description:"",
    image: 'https://i.imgur.com/sFgw8Cal.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://vin-tech.netlify.app/',
    visit: 'https://vin-tech.netlify.app/',
    id: 2,
  },
  {
    title: 'charity web App',
    description: "",
      image: 'https://i.imgur.com/gQWR831l.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://sua-charity.netlify.app/',
    visit: 'https://sua-charity.netlify.app/',
    id: 3,
  },
  {
    title: 'redux gear cart',
    description: "",
    image: 'https://i.imgur.com/UwOTmcPl.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://redux-cart-app.netlify.app/',
    visit: 'https://redux-cart-app.netlify.app/',
    id: 4,
  },
  {
    title: 'Flight Status web app',
    description: "",
    image: 'https://i.imgur.com/rNkyNwhm.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://aviationflightstatus.netlify.app/',
    visit: 'https://aviationflightstatus.netlify.app/',
    id: 6,
  },
  {
    title: 'Joke App',
    description: "",
    image: 'https://i.imgur.com/7gnFdNql.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://jokeapplic.netlify.app/',
    visit: 'https://jokeapplic.netlify.app/',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];